# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-19 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180619_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='org',
        ),
    ]
