# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-22 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20180620_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(default='', max_length=50, verbose_name='就职职位'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='org',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属机构'),
        ),
    ]
