# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-26 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180423_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='email_active_code',
            field=models.BooleanField(default=False, verbose_name='是否使用过链接'),
        ),
    ]
