# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-22 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20180622_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='name',
            new_name='user',
        ),
    ]
